In [7]:
import numpy as np

In [55]:
a = np.array([11, 1.2])
print(a)

[11.   1.2]


In [57]:
print(a.shape)
print(a.ndim)
print(a.dtype)
print(type(a))

(2,)
1
float64
<class 'numpy.ndarray'>


In [9]:
l1 = list(range(10000))

In [11]:
%timeit [x**2 for x in l1]

651 μs ± 2.63 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [13]:
n1 = np.arange(10000)
%timeit n1**2

6.17 μs ± 38.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [25]:
a1 = np.zeros((5,6), dtype = 'int64') #matrix filled with zeros
print(a1) 

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [27]:
a2 = np.ones((2,3)) #matrix filled with ones
print(a2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [63]:
a3 = np.full((4,5), fill_value = 6.9)
print(a3)

[[6.9 6.9 6.9 6.9 6.9]
 [6.9 6.9 6.9 6.9 6.9]
 [6.9 6.9 6.9 6.9 6.9]
 [6.9 6.9 6.9 6.9 6.9]]


In [61]:
a4 = np.empty((4,3))
print(a4)

[[1.01855798e-312 1.10343781e-312 1.01855798e-312]
 [9.54898106e-313 1.01855798e-312 1.01855798e-312]
 [1.23075756e-312 1.03977794e-312 1.01855798e-312]
 [9.76118064e-313 1.10343781e-312 1.90979621e-312]]


In [65]:
a5 = np.eye(4, k = 1, dtype = int)
print(a5)

[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


In [67]:
b = np.arange(9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [69]:
print(np.diag(b))

[0 4 8]


In [105]:
print(np.flipud(b)) #flip the 1st row and last row with each other

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [107]:
print(np.fliplr(b)) #flip the 1st column and last column with each other

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [75]:
b1 = np.eye(3)
print(b1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [77]:
print(np.flipud(b1))

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [81]:
b2 = np.arange(1,10).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [97]:
print(np.flip(b2, axis = 0)) # same works as flipud that means we are  fliping row wise

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [99]:
print(np.flip(b2, axis = 1)) #same works as fliplr that means we are fliping column wise

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [101]:
b3 = np.arange(1,13).reshape(4,3)
print(b3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [103]:
print(np.transpose(b3))

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [109]:
print(b3.reshape(2,2,3))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [111]:
c = np.arange(1,13).reshape(4,-1)
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [115]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [117]:
a1 = a.reshape(10,-1)
print(a1)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [119]:
print(a1.shape)

(10, 1)


In [131]:
b = np.arange(9).reshape(3,3)
print(f'flatten {b.flatten()} and ravel {np.ravel(b)} both methods negates all dimensions excepts one')

flatten [0 1 2 3 4 5 6 7 8] and ravel [0 1 2 3 4 5 6 7 8] both methods negates all dimensions excepts one


In [133]:
c = np.arange(10)
print(c)

[0 1 2 3 4 5 6 7 8 9]


In [137]:
c = np.linspace(0, 5, num = 10, endpoint = True, retstep = True)
print(c)

(array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ]), 0.5555555555555556)


In [161]:
print(np.random.random(size=(3,3)))

[[0.68639978 0.93940343 0.82720454]
 [0.08843936 0.55646515 0.5672129 ]
 [0.82843115 0.16588926 0.98170657]]


In [167]:
print(np.random.binomial(10000, 0.5))

4961


In [171]:
print(np.random.normal(0,1 ,size=(5,2)))

[[-0.14547328 -0.46123674]
 [ 0.42068296 -2.47601947]
 [ 0.99311968  0.54224005]
 [ 1.29183344  0.70350291]
 [-1.33263351  0.35491921]]


In [181]:
a = np.random.randint(0, 12, size = (4,3))

In [183]:
print(a)

[[ 6  2  0]
 [ 3  4  7]
 [ 7  7 11]
 [ 6  3  2]]


In [189]:
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.std(a))
print(np.var(a))

58
0
11
4.833333333333333
2.91070819942883
8.472222222222221


In [193]:
print(np.min(a, axis = 0))
print(np.min(a, axis = 1))

[3 2 0]
[0 3 7 2]
