In [3]:
import numpy as np

In [13]:
a1 = np.arange(4).reshape(2,2)
a2 = np.arange(5,7).reshape(1,2)
print(a1, a2)

[[0 1]
 [2 3]] [[5 6]]


In [17]:
print(np.concatenate((a1, a2), axis = 0))

[[0 1]
 [2 3]
 [5 6]]


In [27]:
print(np.vstack((a1, a2)))

[[0 1]
 [2 3]
 [5 6]]


In [7]:
a1 = np.arange(4).reshape(2,2)
a2 = np.arange(5,7).reshape(2,1)

In [9]:
np.hstack((a1,a2))

array([[0, 1, 5],
       [2, 3, 6]])

In [11]:
a3 = np.hstack((a1,a2))
a3

array([[0, 1, 5],
       [2, 3, 6]])

In [13]:
np.vsplit(a3, 2)

[array([[0, 1, 5]]), array([[2, 3, 6]])]

In [19]:
np.hsplit(a3,3)

[array([[0],
        [2]]),
 array([[1],
        [3]]),
 array([[5],
        [6]])]

In [25]:
np.split(a3, 3, axis = 1)

[array([[0],
        [2]]),
 array([[1],
        [3]]),
 array([[5],
        [6]])]

In [43]:
a = np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
np.split(a,(2,), axis = 1)

[array([[0, 1],
        [3, 4],
        [6, 7]]),
 array([[2],
        [5],
        [8]])]

In [78]:
a = np.array([0,30, 45,60,90])
a

array([ 0, 30, 45, 60, 90])

In [86]:
np.sin(a*np.pi/180)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [99]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a**3

array([[ 1,  8],
       [27, 64]], dtype=int32)

In [101]:
a+b

array([[ 6,  8],
       [10, 12]])

In [103]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [117]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [137]:
print(a[0,:]) # 1st row slicing
print(a[:,0]) #1st column slicing
print(a[0::2, 0::2]) # slicing row and column with a gap
print(a[0:,1:3]) #slicing 1st and 2nd postioned column
print(a[1:3,2:4]) 

[0 1 2 3 4]
[ 0  5 10 15]
[[ 0  2  4]
 [10 12 14]]
[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]]
[[ 7  8]
 [12 13]]


In [139]:
a = np.random.randint(-4,6, (3,4))
print(a)

[[ 0 -4  3  2]
 [ 2  0 -3  4]
 [ 3  1  0 -2]]


In [141]:
a < 0 

array([[False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [143]:
a[a<0]

array([-4, -3, -2])

In [149]:
a[a%2==0]

array([ 0, -4,  2,  2,  0,  4,  0, -2])